beertracker/models/brew.py
"""This file defines the Brew class, to map in the database"""
from beertracker.shared import db

class Brew(db.Model):
    """This class creates the database table as well as the object for describing a brew"""
    id = db.Column(db.Integer, primary_key=True)
    recipe_id = db.Column(db.Integer, db.ForeignKey('recipe.id'), nullable=False)
    brew_og = db.Column(db.Integer, nullable=False)
    brew_fg = db.Column(db.Integer, nullable=True)
    brew_day = db.Column(db.Date, nullable=False)
    brew_done_ferm = db.Column(db.Date, nullable=False)
    brew_comment = db.Column(db.Text)

beertracker/models/recipe.py
"""This file defines the Recipe class, to map in the database"""
from beertracker.shared import db


class Recipe(db.Model):
    """This class creates the database table as well as the object for describing a recipe"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    estimated_og = db.Column(db.Integer, nullable=False)
    estimated_fg = db.Column(db.Integer, nullable=True)
    malt = db.Column(db.JSON(), nullable=False)
    hops = db.Column(db.JSON(), nullable=False)
    mash = db.Column(db.JSON(), nullable=False)
    other = db.Column(db.JSON(), nullable=True)
    before_boil = db.Column(db.Integer, nullable=False)
    yeast = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)

beertracker/blueprints/brews.py
"""Actions for brews"""
from datetime import datetime
from flask import Blueprint, request, redirect, flash, render_template, url_for
from sqlalchemy.exc import SQLAlchemyError, NoResultFound
from beertracker.models.error import FermentingDoneBeforeBrewError
from beertracker.models.brew import Brew
from beertracker.models.recipe import Recipe
from beertracker.shared import db

brew_actions = Blueprint('brew_actions', __name__)


@brew_actions.route('/brew/create', methods=['POST'])
def add_brew() -> redirect:
    """Allows the user to edit the parameters in a specified brew."""
    try:
        recipe_id: int = int(request.form['recipe_id'])
        brew_day: datetime = datetime.strptime(request.form['brew_day'], '%Y-%m-%d')
        brew_og: int = request.form['brew_og']
        brew_fg: int = request.form['brew_fg']
        brew_comment: str = request.form['brew_comment']
        brew_done_ferm: datetime = datetime.strptime(request.form['brew_done_ferm'], '%Y-%m-%d')
        if brew_done_ferm < brew_day:
            raise FermentingDoneBeforeBrewError

        brew = Brew(
            recipe_id=recipe_id,
            brew_og=brew_og,
            brew_fg=brew_fg,
            brew_day=brew_day,
            brew_done_ferm=brew_done_ferm,
            brew_comment=brew_comment
        )
        db.session.add(brew)
        db.session.commit()
    except ValueError:
        flash("The brew could not be created, the input seems to be invalid please try again")
    except FermentingDoneBeforeBrewError:
        flash("Moron! The brew must have been brewn before it is done fermenting.")
    except SQLAlchemyError:
        flash("The brew could not be created due to a unexpected problem with the database")
    finally:
        return redirect('/brews')


@brew_actions.route('/brew/edit/<int:brew_id>')
def edit_brew(brew_id: int) -> render_template:
    brew: Brew = Brew.query.get_or_404(brew_id)
    recipe: Recipe = Recipe.query.get_or_404(brew.recipe_id)
    return render_template('edit/brew.html', brew=brew, recipe=recipe)


@brew_actions.route('/brew/edit', methods=['POST'])
def modify_brew() -> redirect:
    try:
        brew_id: int = request.form['brew_id']
        brew_og: int = request.form['brew_og']
        brew_fg: int = request.form['brew_fg']
        brew_done_fermenting: datetime = datetime.strptime(request.form['brew_done_ferm'],
                                                           '%Y-%m-%d')
        brew_day: datetime = datetime.strptime(request.form['brew_day'], '%Y-%m-%d')
        brew_comment: str = request.form['brew_comment']

        brew = Brew.query.get(brew_id)

        if brew is None:
            raise NoResultFound()

        brew.brew_og = brew_og
        brew.brew_fg = brew_fg
        brew.brew_comment = brew_comment
        brew.brew_done_fermenting = brew_done_fermenting
        brew.brew_day = brew_day

        db.session.add(brew)
        db.session.commit()
    except NoResultFound:
        flash("The brew could not be updated because it is not found.")
    except ValueError:
        flash("The brew could not be updated, the input seems to be invalid please try again")
    finally:
        return redirect('/brews')


@brew_actions.route('/brews')
def brews() -> render_template:
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    today = datetime.now().date()
    all_brews = db.session.query(Brew, Recipe).join(Recipe).filter(Brew.recipe_id == Recipe.id). \
        order_by(Brew.brew_day.desc()).paginate(page=page, per_page=per_page)
    return render_template('brews.html', brews=all_brews, today=today)


@brew_actions.route('/brew/find', methods=['POST'])
def find_brew() -> redirect:
    brew_id: int = request.form['brew_id']
    try:
        brew = Brew.query.get(brew_id)

        if brew is None:
            raise NoResultFound()

        return redirect(url_for('brew_actions.view_brew', brew_id=brew_id))
    except NoResultFound:
        flash("Invalid brew ID")

    return redirect(url_for('dashboard_actions.dashboard'))


@brew_actions.route('/brew/view/<int:brew_id>')
def view_brew(brew_id: int) -> render_template:
    display_brew = db.session.query(Brew, Recipe).filter(Brew.id == brew_id).join(Recipe).filter(
        Brew.recipe_id == Recipe.id).first()
    return render_template('brew.html', brew=display_brew)

beertracker/blueprints/dashboard.py
"""Actions for brews"""
from datetime import datetime
from flask import Blueprint, render_template
from sqlalchemy import func
from sqlalchemy.exc import SQLAlchemyError, NoResultFound
from beertracker.models.brew import Brew
from beertracker.models.recipe import Recipe
from beertracker.shared import db

dashboard_actions = Blueprint('dashboard_actions', __name__)

@dashboard_actions.route('/')
def dashboard() -> render_template:
    brews_per_month = db.session.query(func.strftime('%Y-%m', Brew.brew_day), func.avg(Brew.id)).group_by(func.strftime('%m', Brew.brew_day)).limit(12).all()
    today = datetime.now().date()
    fermenting_brews = db.session.query(Brew, Recipe).filter(Brew.brew_day >= today).join(Recipe).filter(Brew.recipe_id == Recipe.id).order_by(Brew.brew_day.desc())
    return render_template('dashboard.html', fermenting_brews=fermenting_brews, today=today, monthly_chart=brews_per_month)

beertracker/blueprints/recipes.py
from flask import Blueprint, request, redirect, flash, render_template
from beertracker.models.recipe import Recipe
from beertracker.shared import db

recipe_actions = Blueprint('recipe_actions', __name__)


@recipe_actions.route('/recipes')
def recipes():
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)
    recipes = Recipe.query.paginate(per_page=per_page, page=page)
    return render_template('recipes.html', recipes=recipes, per_page=per_page)


@recipe_actions.route('/recipe/create', methods=['GET'])
def create_recipe() -> render_template:
    return render_template('create/recipe.html')


@recipe_actions.route('/recipe/create', methods=['POST'])
def add_recipe() -> redirect:
    hops = []
    no_hops: int = int(request.form.get('no_hops'))
    hop_names = request.form.getlist('hop[]')
    hop_amount = request.form.getlist('hop_amount[]')
    hop_boil = request.form.getlist('hop_boil[]')
    hops_ok = no_hops == len(hop_names) and no_hops == len(hop_amount) and no_hops == len(hop_boil)

    malt = []
    no_malt: int = int(request.form.get('no_malts'))
    malt_names = request.form.getlist('malt[]')
    malt_amount = request.form.getlist('malt_amount[]')
    malts_ok = no_malt == len(malt_names) and no_malt == len(malt_amount)

    mash = []
    no_mash: int = int(request.form.get('no_mash'))
    mash_stages = request.form.getlist('mash[]')
    mash_temps = request.form.getlist('mash_temp[]')
    mash_durations = request.form.getlist('mash_duration[]')
    mash_ok = no_mash == len(mash_stages) and no_mash == len(mash_temps) and no_mash == len(
        mash_durations)

    other = []
    no_other: int = int(request.form.get('no_other'))
    other_name = request.form.getlist('other_name[]')
    other_amount = request.form.getlist('other_amount[]')
    other_time = request.form.getlist('other_time[]')
    other_ok = no_other == len(other_name) and no_other == len(other_amount) and no_other == len(
        other_name)

    before_boil = request.form.get('before_boil')
    estimated_og = request.form.get('estimated_og')
    estimated_fg = request.form.get('estimated_fg')
    name = request.form.get('name')
    yeast = request.form.get('yeast')
    description = request.form.get('description')

    if hops_ok and malts_ok and mash_ok and other_ok:
        for i in range(no_hops):
            hops.append({"name": hop_names[i], "amount": hop_amount[i], "boil": hop_boil[i]})
        for i in range(no_malt):
            malt.append({"name": malt_names[i], "amount": malt_amount[i]})
        for i in range(no_mash):
            mash.append(
                {"name": mash_stages[i], "temp": mash_temps[i], "duration": mash_durations[i]})
        for i in range(no_other):
            other.append({"name": other_name[i], "amount": other_amount[i], "time": other_time[i]})

    try:
        new_recipe = Recipe(
            name=name,
            before_boil=before_boil,
            mash=mash,
            estimated_fg=estimated_fg,
            estimated_og=estimated_og,
            hops=hops,
            malt=malt,
            yeast=yeast,
            other=other,
            description=description
        )
        db.session.add(new_recipe)
        db.session.commit()
    except ValueError:
        flash("The recipe could not be created due to invalid inputs.")
    finally:
        return redirect("/recipes")


@recipe_actions.route('/recipe/<int:recipe_id>')
def recipe(recipe_id: int) -> render_template:
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template('recipe.html', recipe=recipe)


@recipe_actions.route('/brew/recipe/<int:recipe_id>')
def brew_recipe(recipe_id: int) -> render_template:
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template('create/brew.html', recipe=recipe)

beertracker/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='application.css') }}">
  <script src="{{ url_for('static', filename='js/chart.js') }}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Beertracker</title>
</head>

<body>
  <script>
    $(function () {
      $('[data-toggle="popover"]').popover()
    })
  </script>
  <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <a class="navbar-brand" href="/">
      Beertracker v1.0
    </a>
     <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
	<li class="nav-item">
          <a class="nav-link" href="/">Dashboard</a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/brews">Brews</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recipes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/recipes">View Recipes</a>
            <a class="dropdown-item" href="/recipe/create">Create recipe</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>

  {% with messages = get_flashed_messages() %}
    {% for message in messages %}
      {% set message_class = "alert-danger" %}
      <div class="alert {{ message_class }}" role="alert">
        {{ message }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
      </div>
    {% endfor %}
  {% endwith %}
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

beertracker/templates/brew.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>{{ brew.Recipe.name }} <small>{{ brew.Brew.id }}</small></h1>

        {% if brew.Recipe.comment %}
            <p>{{ brew.Recipe.comment }}</p>
        {% endif %}
        <div class="row">
            <div class="col-md-6">
                <h2>Ingredients</h2>
                <div class="row">

                    <div class="col-md-12">
                        <h3>Malts</h3>

                        <table class="table table-striped">
                            <thead class="thead-dark">
                            <tr>
                                <th>Name</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for malt in brew.Recipe.malt %}
                            <tr>
                                <td>{{ malt.name }}</td>
                                <td>{{ malt.amount }} kg</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>

                    <div class="col-md-12">
                        <h3>Mashing</h3>
                        <table class="table table-striped">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Stage</th>
                                    <th>Temperature</th>
                                    <th>Duration</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for mash in brew.Recipe.mash %}
                            <tr>
                                <td>{{ mash.name }}</td>
                                <td>{{ mash.temp }} °C</td>
                                <td>{{ mash.duration }} minutes</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="col-md-12">
                        <h3>Hops</h3>
                        <table class="table table-striped">
                            <thead class="thead-dark">
                            <tr>
                                <th>Hop</th>
                                <th>Amount</th>
                                <th>Boil time</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for hop in brew.Recipe.hops %}
                            <tr>
                                <td>{{ hop.name }}</td>
                                <td>{{ hop.amount }} g</td>
                                <td>{{ hop.boil }} minutes</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="col-md-12">
                        <h3>Other</h3>
                        <table class="table table-striped">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Name</th>
                                    <th>Amount</th>
                                    <th>Time</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for other in brew.Recipe.other %}
                                <tr>
                                    <td>{{ other.name }}</td>
                                    <td>{{ other.amount }}</td>
                                    <td>{{ other.time }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>

            <div class="col-md-6">
                <h2>Other Information</h2>
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td><b>Yeast used:</b></td>
                            <td>{{ brew.Recipe.yeast }}</td>
                        </tr>
                        <tr>
                            <td><b>Recommended volume of wort before boil:</b></td>
                            <td>{{ brew.Recipe.before_boil }} L</td>
                        </tr>

                        <tr>
                            <td><b>OG</b></td>
                            <td>{{ brew.Brew.brew_og }}</td>
                        </tr>

                        <tr>
                            <td><b>FG</b></td>
                            <td>{{ brew.Brew.brew_fg }}</td>
                        </tr>

                        <tr>
                            {% if brew.Brew.brew_og and brew.Brew.brew_fg %}
                                <td><b>ABV</b></td>
                                <td>{{ ((brew.Brew.brew_og - brew.Brew.brew_fg) / 7.62) | round(2) }}%</td>
                            {% else %}
                                <td><b>Estimated ABV</b></td>
                                <td>{{ ((brew.Recipe.estimated_og - brew.Recipe.estimated_fg) / 7.62) | round(2) }}%</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td><b>Brewed:</b></td>
                            <td>{{ brew.Brew.brew_day }}</td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

beertracker/templates/brews.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-10">
      <h1>Brews</h1>
        {% if not brews.items %}
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">No brews</h4>
            <p>
              You have not created any brews yet, to create one start by adding a recipe <a href="{{ url_for('recipe_actions.create_recipe') }}">here</a>!<br>
              When you're done go to the <a href="{{ url_for('recipe_actions.recipes') }}">Recipes view</a> and choose brew.
            </p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        <table class="table table-striped">
          <thead class="thead-dark">
            <tr>
              <th>Brew ID</th>
              <th>Recipe</th>
              <th>Date Brewed</th>
              <th>OG</th>
              <th>FG</th>
              <th>Abv</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for brew in brews.items %}
            <tr>
              <td><a href="/brew/edit/{{ brew.Brew.id }}">#{{ brew.Brew.id }}</a></td>
              <td><a href="/recipe/{{ brew[1].id }}">{{ brew.Recipe.name }}</a></td>
              <td>{{ brew.Brew.brew_day }}</td>
              <td>{{ brew.Brew.brew_og }}</td>
              <td>{{ brew.Brew.brew_fg }}</td>
              <td>{% if brew.Brew.brew_fg %} {{ ((brew.Brew.brew_og - brew.Brew.brew_fg) / 7.62) | round(2) }} %  {% else %} Not Available {% endif %}</td>
              <td>
                {% set factor = (today - brew[0].brew_day).days / (brew[0].brew_done_ferm - brew[0].brew_day).days %}
                {% if factor >= 1 %}
                  Drinkable
                {% else %}
                  <div class="progress">
                    <div class="progress-bar {% if factor >= 1 %} bg-success {% endif %} " role="progressbar" style="width: {{ factor*100 }}%;" aria-valuenow="{{ factor*100 }}" aria-valuemin="0" aria-valuemax="100">
                      {{ (factor*100) | round(0) }}%
                    </div>
                  </div>
                {% endif %}
              </td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
        <nav aria-label="Pagination" class="pull-right">
          <ul class="pagination">
              <li class="page-item"><a class="page-link {% if brews.page == 1 %}disabled{% endif %}" href="{{ url_for('brew_actions.brews', page=brews.prev_num) }}">Previous</a></li>
              {% for page_num in brews.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num == brews.page  %}
                  <li class="page-item active"><a class="page-link" href="{{ url_for('brew_actions.brews', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="{{ url_for('brew_actions.brews', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
              {% endfor %}
            <li class="page-item"><a class="page-link {% if brews.page == brews.pages %}disabled{% endif %}" href="{{ url_for('brew_actions.brews', page=brews.next_num) }}">Next</a></li>
          </ul>
        </nav>
    </div>
</div>
{% endblock content %}

beertracker/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-9">
      <h1>Welcome to Beertracker</h1>
      <h2>Fermenting beers</h2>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Brew ID</th>
            <th>Recipe</th>
            <th>Date Brewed</th>
            <th>Fermenting done</th>
            <th>OG</th>
            <th>FG</th>
            <th>Abv</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
        {% for fermenting_brew in fermenting_brews %}
          <tr>
            <td><a href="/brew/edit/{{ fermenting_brew[0].id }}">#{{ fermenting_brew[0].id }}</a></td>
            <td><a href="/recipe/{{ fermenting_brew[1].id }}">{{ fermenting_brew[1].name }}</a></td>
            <td>{{ fermenting_brew.Brew.brew_day }}</td>
            <td>{{ fermenting_brew.Brew.brew_done_ferm }}</td>
            <td>{{ fermenting_brew.Brew.brew_og }}</td>
            <td>{{ fermenting_brew.Brew.brew_fg }}</td>
            <td>{% if fermenting_brew.Brew.brew_fg %} {{ ((fermenting_brew.Brew.brew_og - fermenting_brew.Brew.brew_fg) / 7.62) | round(2) }} {% else %} est. {{ ((fermenting_brew.Recipe.estimated_og - fermenting_brew.Recipe.estimated_fg) / 7.62) | round(2) }} {% endif %} %</td>
            <td>
              {% set factor = (today - fermenting_brew[0].brew_day).days / (fermenting_brew[0].brew_done_ferm - fermenting_brew[0].brew_day).days %}
              {% if factor >= 1 %}
                Drinkable
              {% else %}
                <div class="progress">
                  <div class="progress-bar {% if factor >= 1 %} bg-success {% endif %} " role="progressbar" style="width: {{ factor*100 }}%;" aria-valuenow="{{ factor*100 }}" aria-valuemin="0" aria-valuemax="100">
                      {{ (factor*100) | round(0) }}%
                  </div>
                </div>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <h2>Interesting facts</h2>
      <canvas id="brew_chart"></canvas>
      <script>
      const ctx = document.getElementById('brew_chart').getContext('2d');
      const brew_chart = new Chart(ctx, {
          type: 'line',
          data: {
              labels: [
                {% for e in monthly_chart %}
                  '{{ e[0] }}',
                {% endfor %}
              ],
              datasets: [{
                  label: 'Brews per month',
                  data: [
                    {% for e in monthly_chart %}
                      '{{ e[1] }}',
                    {% endfor %}
                  ],
                  borderWidth: 1,
                  backgroundColor: '#dc3545',
                  borderColor: '#dc3545',
              }]
          },
          options: {
              scales: {
                  y: {
                      beginAtZero: true
                  }
              }
          }
      });
      </script>

    </div>
    <div class="col-md-3">
      <div class="row">
        <h2>Quick search</h2>
        <form action="brew/find" method="POST">
          <p>
            If you're curious about a specified brew for example one that you have found in the garage under a large pile of junk, enter the brew ID here and press return.
            You'll be showed the recipe and the parameters for that beer.
          </p>
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text">#</div>
            </div>
            <input type="number" class="form-control" name="brew_id" placeholder="e.g 13" required>
            <div class="input-group-append">
              <button class="btn btn-success" type="submit">
                <i class="bi bi-search"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
</div>
{% endblock content %}

beertracker/templates/recipes.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-10">
      <h1>Recipes</h1>

      {% if not recipes.items %}
        <div class="alert alert-danger" role="alert">
          <h4 class="alert-heading">No recipes!</h4>
          <p>
            You have not created any recipes yet, to create one start by adding a recipe <a href="{{ url_for('recipe_actions.create_recipe') }}">here</a>!<br>
          </p>
        </div>
      {% endif %}

      <p>This is the main CRUD for the recipes, to create a new recipe click <a href="{{ url_for('recipe_actions.create_recipe') }}">here.</a></p>
      <p>
        For the time being it is not possible to edit a recipe, due to my laziness and lack of time to build Beertracking applications.
        <br>
        Also the recipes should be able to be exported as pdfs, to easily share them. This function is also missing.
      </p>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Name</th>
            <th>Batch size</th>
            <th>Estimated OG</th>
            <th>Estimated FG</th>
            <th>Estimated ABV</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for recipe in recipes.items %}
            <tr>
              <td><a href="/recipe/{{ recipe.id }}">{{ recipe.name }}</a></td>
              <td>{{ recipe.before_boil }} L</td>
              <td>{{ recipe.estimated_og }}</td>
              <td>{{ recipe.estimated_fg }}</td>
              <td>{{ ((recipe.estimated_og - recipe.estimated_fg) / 7.62) | round(2) }}%</td>
              <td>
                <a class="btn btn-success btn-sm" href="/recipe/{{ recipe.id }}">View</a>
                <a class="btn btn-primary btn-sm" href="/brew/recipe/{{ recipe.id }}">Make a brew from this recipe</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="row">
        <nav aria-label="Pagination" class="pull-right">
          <ul class="pagination">
              <li class="page-item"><a class="page-link {% if recipes.page == 1 %}disabled{% endif %}" href="{{ url_for('recipe_actions.recipes', page=recipes.prev_num) }}">Previous</a></li>
              {% for page_num in recipes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num == recipes.page  %}
                    <li class="page-item active"><a class="page-link" href="{{ url_for('recipe_actions.recipes', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="{{ url_for('recipe_actions.recipes', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
              {% endfor %}
            <li class="page-item"><a class="page-link {% if recipes.page == recipes.pages %}disabled{% endif %}" href="{{ url_for('recipe_actions.recipes', page=recipes.next_num) }}">Next</a></li>
          </ul>
        </nav>

        Displaying 10 entities per page
      </div>
    </div>
</div>
{% endblock content %}